### ISSUE TITLE
Bug in latest update 2/17/2016

### ISSUE THREAD

**Issue by Brunes** [splewis/csgo-multi-1v1#145]
Hi guys,
I have a big problem with this plugin on  my server. After latest csgo update, players can't join to team. Every two seconds, the round restarts.

Chat:
> Sorry, all the arenas are currently full.
You are in position 1 in the waiting queue.

Server log:
`L 02/18/2016 - 14:20:26: Team "CT" scored "0" with "0" players
L 02/18/2016 - 14:20:26: Team "TERRORIST" scored "0" with "0" players
L 02/18/2016 - 14:20:26: World triggered "Round_End"
L 02/18/2016 - 14:20:28: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT "0") (T "0")
L 02/18/2016 - 14:20:28: Team "CT" scored "0" with "0" players
L 02/18/2016 - 14:20:28: Team "TERRORIST" scored "0" with "0" players
L 02/18/2016 - 14:20:28: World triggered "Round_End"
L 02/18/2016 - 14:20:30: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT `

`L 02/18/2016 - 04:34:35: Info (map "am_loot") (file "errors_20160218.log")
L 02/18/2016 - 04:34:35: [multi1v1.smx] No arenas could be found for this map!
L 02/18/2016 - 05:05:36: Error log file session closed.
L 02/18/2016 - 05:05:36: SourceMod error session started`

Can someone help me?
Thanks.

**Comment by splewis** [comment]
Update to the latest version: https://forums.alliedmods.net/showpost.php?p=2393943&postcount=998

**Comment by zAfLu** [comment]
update works fine for me

**Comment by Brunes** [comment]
resolved. Thanks.

**Comment by RyPope** [comment]
I'm still having this issue after updating to 1.1.3 and SM to 1.7.3
